version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
    - method: pip
      path: sphinx_rtd_theme

