name: expipe-test
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - h5py
  - cython
  - pandas
  - seaborn
  - pyyaml
  - pytest
  - nose
  - jupyter
  - astropy
  - pip:
    - quantities
