package:
  name: expipe
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
    noarch: python  
    script:
      - pip install pyrebase quantities
      - python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - pip
    - numpy

  run:
    - python
    - setuptools
    - pip
    - pyyaml
    - numpy

test:
  imports:
    - expipe
  requires:
    - sphinx

about:
  home: https://github.com/CINPLA/expipe/
  license: GPLv3
  license_file: LICENSE
