package:
  name: expipe
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
    noarch: python
    script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pip
    - pyyaml
    - numpy

# NOTE cannot do tests here beacuse of pyrebase from pip (issues with noarch), but is tested in travis

about:
  home: https://github.com/CINPLA/expipe/
  license: GPLv3
  license_file: LICENSE
