package:
  name: expipe
  version: {{ environ.get("GIT_STRING", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
    noarch: python
    script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pip
    - pyyaml
    - numpy
    - quantities ==0.12.1

test:
  source_files:
    - expipe
  requires:
    - pytest
    - dpath
    - coverage
    - codecov
  imports:
    - expipe
  commands:
    - coverage run --source expipe --omit expipe/_version.py -m py.test -s
    - coverage report
    - codecov

about:
  home: https://github.com/CINPLA/expipe/
  license: GPLv3
  license_file: LICENSE
