package:
  name: expipe
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
    # noarch: python  # TODO Add back noarch when it works properly on Windows,
                      # we are converting packages manually now
    script: pip install pytest pytest-cov pytest-pep8 coveralls pyrebase && python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyyaml
    - pip
    - quantities

  run:
    - python
    - setuptools
    - pip
    - pyyaml
    - quantities
    - numpy

test:
  imports:
    - expipe
  commands:
    - py.test ../expipe/io/tests --doctest-modules --doctest-glob='*.rst' --pep8 ../expipe -v --cov ../expipe --cov-report term-missing

  requires:
    - sphinx

about:
  home: https://github.com/CINPLA/expipe/
  license: GPLv3
  license_file: LICENSE
