name: Test on Ubuntu

on:
  pull_request:
      branches: [master]
      types: [synchronize, opened, reopened]


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    - name: Pytest
      run: |
        pytest -v
